version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER: jawa
       POSTGRES_PASSWORD: Diveinn!@3
       POSTGRES_DB: fanteam
       POSTGRES_PORT: 5132
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5132:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
