# Generated by Django 2.2.1 on 2019-08-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='players/pics/default.jpg', upload_to='players/pics'),
        ),
    ]
