# Generated by Django 2.2.1 on 2019-08-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantacysport',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='INACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='media/default/team.png', upload_to='media/team/pics'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
            ],
        ),
    ]
