# Generated by Django 2.2.1 on 2019-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fantacyapp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerequest',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
