# Generated by Django 2.2.1 on 2019-08-24 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantacysport',
            name='fantacy_rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
