# Generated by Django 2.2.1 on 2019-08-24 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fantacysport_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='power_pics',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
