# Generated by Django 2.2.1 on 2019-09-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_match_power_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.FantacySport'),
            preserve_default=False,
        ),
    ]
