# Generated by Django 2.2.1 on 2019-09-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_match_fantacyapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gender',
            field=models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN')], default='me', max_length=10),
        ),
        migrations.AlterField(
            model_name='fantacyapp',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='INACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='fantacysport',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='INACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
